export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-300 p-1">
          <p>Header</p>
        </header>
        {children}
        <footer className="bg-gray-500 1p">Footer</footer>
      </body>
    </html>
  );
}
